news/urls.py
from django.urls import path
from .views import NewsListView

app_name = 'news'

urlpatterns = [
    path('', NewsListView.as_view(), name='news_list')
]

news_paper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from post.views import LandingPage
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('post.urls', namespace='post')),
    path('news/', include('news.urls', namespace='news')),
    path('', LandingPage.as_view(), name='landing_page'),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('login/',LoginView.as_view(),name='login'),
    # path('signup/', SignUpView.as_view(), name='signup'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView


app_name = 'post'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('create/', PostCreateView.as_view(), name='post_creat')
]

news/models.py
from django.db import models
from post.models import Category
from ckeditor.fields import RichTextField


class New(models.Model):
    img = models.ImageField(upload_to='PROJECT_FOR_THE_LESSON/image', verbose_name='PhotoN', blank=True)
    title = models.CharField(max_length=40)
    preview_info = RichTextField()
    information = RichTextField()
    posted_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

post/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name}'

class Post(models.Model):
    img = models.ImageField(upload_to='PROJECT_FOR_THE_LESSON/image/', verbose_name='PhotoP', blank=True)
    title = models.CharField(max_length=30)
    rating_stars = models.IntegerField(validators=[MinValueValidator(0) ,MaxValueValidator(5)])
    description = models.TextField()
    released_date = models.DateField()
    posted_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    trailer_pattern = models.URLField(None)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('post:post_detail', args=[str(self.id)])

post/forms.py
from unicodedata import category
from django import forms
from .models import Post, Category
from django.core.validators import MinValueValidator, MaxValueValidator

news/views.py
from django.shortcuts import render
from django.views import generic
from .models import New


class NewsListView(generic.ListView):
    template_name = 'news/news-list.html'
    queryset = New.objects.all()
    context_object_name = 'news'

class NewsDetailView(generic.DetailView):
    template_name = 'news/news-detail.html'
    queryset = New.objects.all()
    context_object_name = 'new'

post/views.py
from django.views import generic
from django.views.generic.edit import CreateView
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Post


class PostListView(generic.ListView):

    template_name ='post/post-list.html'
    queryset = Post.objects.all()
    context_object_name = 'posts'

class PostDetailView(generic.DetailView):

    template_name = 'post/post-detail.html'
    queryset = Post.objects.all()
    context_object_name = 'post'

# class PostCreateView(generic.CreateView):
#     template_name = 'post/post-create.html'
#     form_class = PostModelCreateForm

#     def get_success_url(self):
#         return reverse('post:post_list')
    
class LandingPage(generic.TemplateView):
    template_name = 'landing-page.html'

# New version
class PostCreateView(CreateView):
    template_name = 'post/post-create.html'
    model = Post
    fields = [
        'img',
        'title',
        'rating_stars',
        'description',
        'released_date',
        'category',
        'trailer_pattern'
    ]

# Old version
# def Create(request):
#     if request.method == 'POST':
#         create = Post()

#         create.title = request.POST.get('title')
#         create.rating_stars = request.POST.get('rating_stars')
#         create.description = request.POST.get('description')
#         create.released_date = request.POST.get('released_date')
#         create.category = request.POST.get('category')
#         create.category = request.POST.get('trailer_pattern')

#         if len(request.FILES) != 0:
#             create.img = request.FILES['img']
#         create.save()
#         return redirect('posts:post_list')
#     return render(request , 'post/post-create.html')

news/templates/news/news-detail.html
{% extends 'base.html' %}

{% block title %}
  Detail
{% endblock %}

{% block content %}
  <script src="https://cdn.tailwindcss.com"></script>
  <section class="text-gray-600 body-font">
    <style>
      body {
        background-color: #0B1858;
        background-repeat: no-repeat;
        background-size: 150%;
      }
    </style>
      <div class="container px-3 py-24 mx-auto">
          <div class="xl:w-1/2 lg:w-3/4 w-full mx-auto text-left">
              <img class="max-w-full h-auto rounded-lg" src="{{new.img.url}}" alt="blog">
              <p class="leading-relaxed text-sky-100">
                  Постановщик фильма "007: Координаты "Скайфолл" сделал предположение о развитии "бондианы"
                  Сэм Мендес, снявший два из пяти фильмов "бондианы" с участием Дэниела Крэйга, вряд ли готов снять еще одну 
                  картину о Бонде, однако полагает, что постановщиком следующего фильма об агенте 007 должна быть женщина. Мендес,
                  продвигая свой новый проект "Империя света", вспомнил свой опыт работы в знаменитой шпионской франшизе, которая
                  после 25-го эпизода должна перезагрузиться с новым актером в роли агента с лицензией на убийство и постановщиком,
                  который представит его взыскательной фанбазе.<br><br>

                  "Я не думаю, что я им еще нужен. Это был невероятный проект в тот момент моей жизни; я и мечтать не мог о лучшем.
                  Я увидел мир по-другому", - в частности сказал режиссер о создании фильмов "007: Спектр" и "007: Координаты "Скайфолл",
                  особенно "Скайфолл".<br><br>

                  Снимать фильмы о Бонде, по его словам, было все равно что быть инженером в такой же степени, как и режиссером. "Это все равно,
                  что возводить строительные леса и строить целый мир... В каком-то смысле это даже утомительно, но по-другому".<br><br>

                  Но боевики эволюционируют, и использование компьютерной графики не стоит на месте, и, по словам Мендеса, Бонд тоже должен 
                  развиваться. Он сочувствует Барбаре Брокколи и Майклу Дж. Уилсону, "хранителям пламени Бонда". "Не позавидуешь тому, как Барбаре 
                  приходилось следить за пятью фильмами Дэниела. Он придал новый импульс франшизе, но франшиза настолько огромна, что молодому 
                  актеру очень трудно войти в нее".<br><br>

                  На вопрос, предлагали ли Мендесу пост режиссеру нового фильма о Бонде, он ответил, смеясь: "Позвольте мне перефразировать. Я
                  думаю, что актер, играющий Бонда, будет развиваться, режиссер должен развиваться. Я думаю, было бы здорово увидеть женщину 
                  в качестве режиссера "бондианы". Я думаю, это было бы замечательно".<br><br>
                  </p><br><br>
                  <a class="text-purple-600 inline-flex items-center md:mb-2 lg:mb-0" href="D:\news\news.html">Обратно<br>
                      <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M5 12h14"></path>
                        <path d="M12 5l7 7-7 7"></path>
                      </svg>
                    </a>
              <span class=" h-2 w-10 rounded bg-indigo-500 mt-5 mb-6"></span>
              <h2 class="text-white font-medium title-font tracking-wider text-sm">Властелин Колец</h2>
              <p class="text-sky-100">Python Developers</p>
      </div>
  </section>
{% endblock %}

news/templates/news/news-list.html
{% extends 'base.html' %}

{% block title %}
  News list
{% endblock %}

{% block content %}
  <style>
    body {
      background-color: #171b34;
    }
  </style>
  <h2 class="text-3xl tracking-tight font-bold text-white-900 mt-10 mb-4 text-white">Последние новости</h2> 
  
  <section class="text-gray-600 body-font">
    <div class="container-fluid px-5 py-16 mx-auto">
      <div class="flex flex-wrap -m-4">
        {% for new in news %}   
          <div class="mx-1 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
            <a href="#">
                <img class="w-30 h-30
                object-cover object-center rounded-t-lg" src="{{ new.img.url }}" alt="">
            </a>
            <div class="p-5">
                <a href="#">
                    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5>
                </a>
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
                <a href="#" class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    Read more
                    <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                </a>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}

post/templates/post/post-create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block title %}
    Create post
{% endblock %}

{% block content %}
    <form method="post" class="mx-24 my-24">
        {% csrf_token %}
        {{ form|crispy }}
        <button href="{% url 'post:post_list' %}" class="w-full bg-blue-500 text-white rounded-md hover:bg-blue-600 px py-1" type="submit">
            Submit
        </button>
    </form>
{% endblock %}

post/templates/post/post-detail.html
{% extends 'base.html' %}

{% block title %}
    Detail
{% endblock %}

{% block content %}
    <section class="text-gray-400 bg-gray-900 body-font">
        <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <div class="w-64 h-96 md:mb-0 mb-10">
              <img class="object-cover object-center rounded" alt="hero" src="{{ post.img.url }}">
          </div>
          <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
              <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">{{post.title}}
                  <br class="hidden lg:inline-block">{{post.released_date}}
              </h1>
              <p class="mb-8 leading-relaxed">{{post.description}}.</p>
              <div class="flex justify-center">
                <a href="">
                  <button class="inline-flex text-white bg-purple-500 border-0 py-2 px-6 focus:outline-none hover:bg-purple-600 rounded text-lg">
                    Click for watch
                  </button>
                </a>
              </div>
          </div>
        </div>
    </section>

    <section class="text-gray-400 bg-gray-900 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
          <div class="flex w-full mb-20 flex-wrap">
            <h1 class="sm:text-3xl text-2xl font-medium title-font text-white lg:w-1/3 lg:mb-0 mb-4">Some interesting cadres</h1>
            <p class="lg:pl-6 lg:w-2/3 mx-auto leading-relaxed text-base">It's here because you'll learn more about the film's graphics with this one.<br> And you will know what you are going to watch.</p>
          </div>
          <div class="flex flex-wrap md:-m-2 -m-1">
            <div class="flex flex-wrap w-1/2">
              <div class="md:p-2 p-1 w-1/2">
                <img alt="gallery" class="w-full object-cover h-full object-center block" src="https://dummyimage.com/500x300">
              </div>
              <div class="md:p-2 p-1 w-1/2">
                <img alt="gallery" class="w-full object-cover h-full object-center block" src="https://dummyimage.com/501x301">
              </div>
              <div class="md:p-2 p-1 w-full">
                <img alt="gallery" class="w-full h-full object-cover object-center block" src="https://dummyimage.com/600x360">
              </div>
            </div>
            <div class="flex flex-wrap w-1/2">
              <div class="md:p-2 p-1 w-full">
                <img alt="gallery" class="w-full h-full object-cover object-center block" src="https://dummyimage.com/601x361">
              </div>
              <div class="md:p-2 p-1 w-1/2">
                <img alt="gallery" class="w-full object-cover h-full object-center block" src="https://dummyimage.com/502x302">
              </div>
              <div class="md:p-2 p-1 w-1/2">
                <img alt="gallery" class="w-full object-cover h-full object-center block" src="https://dummyimage.com/503x303">
              </div>
            </div>
          </div>
        </div>
      <div class="ratio ratio-16x9 mx-auto w-4/5">
        <iframe src="{{ post.trailer_pattern }}" title="YouTube video" allowfullscreen></iframe>
      </div>
    </section>
{% endblock %}

post/templates/post/post-list.html
{% extends 'base.html' %}

{% block title %}
    Post List
{% endblock %}


{% block content %}
        <div class="container py-6 bg-black">
            <div class="flex flex-wrap justify-center">
                {% for post in posts %}
                    <a href="{% url 'post:post_detail' post.pk %}">
                        <div class="flex relative mb-4 mx-1 w-64 h-96
                            scale-100 hover:scale-105 ease-in duration-300">
                            {% if post.img %}
                            <img alt="gallery" class="absolute inset-0 w-full h-full
                                object-cover object-center"
                                src="{{ post.img.url }}">
                            {% endif %}
                            <div class="px-8 py-10 relative z-10 w-full border-4
                                border-gray-200 bg-[#0f172a] opacity-0 
                                hover:opacity-100 ease-in duration-300">
                                <h2 class="tracking-widest text-sm title-font font-medium
                                    text-indigo-500 mb-1">{{post.title}}</h2>
                                <h1 class="title-font text-lg font-medium 
                                    text-orange-200 mb-3">{{post.rarting_stars}}</h1>
                                <p class="text-cyan-700 leading-relaxed">{{post.description | slice:':150'}}....</p>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous"> -->
    <script src="https://cdn.tailwindcss.com"></script>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
</body>
</html>

templates/create.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block content %}
    <br>
    <br>
    <h1>News create</h1>
    <br>
    <br>
    
    <section class="section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h2 class="fw-bold">Add News</h2>
                        </div>
                        <div class="card-body">
                            <form action="" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="" class="form-label">Name</label>
                                    <input type="text" Required name="title" class="form-control">
                                </div>
                                <div class="mb-3">
                                    <label for="" class="form-label">Description</label>
                                    <input type="text" Required name="rating_stars" class="form-control">
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
                                    <textarea class="form-control" Required name="description" id="exampleFormControlTextarea1" rows="3"></textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
                                    <textarea class="form-control" Required name="released_date" id="exampleFormControlTextarea1" rows="3"></textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
                                    <textarea class="form-control" Required name="category" id="exampleFormControlTextarea1" rows="3"></textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
                                    <textarea class="form-control" Required name="trailer_pattern" id="exampleFormControlTextarea1" rows="3"></textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="" class="form-label">Image</label>
                                    <input type="file" Required name="ime" class="form-control">
                                </div>
                                <button class="btn btn-dark">Save</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><br>
    <br>
    <br>
{% endblock %}

templates/footer.html
<footer class="text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-wrap md:text-left text-center order-first">
        <div class="lg:w-1/4 md:w-1/2 w-full px-4">
          <h2 class="title-font font-medium text-white tracking-widest text-sm mb-3">CATEGORIES</h2>
          <nav class="list-none mb-10">
            <li>
              <a class="text-gray-400 hover:text-white">First Link</a>
            </li>
            <li>
              <a class="text-gray-400 hover:text-white">Second Link</a>
            </li>
            <li>
              <a class="text-gray-400 hover:text-white">Third Link</a>
            </li>
            <li>
              <a class="text-gray-400 hover:text-white">Fourth Link</a>
            </li>
          </nav>
        </div>
        <div class="lg:w-1/4 md:w-1/2 w-full px-4">
          <h2 class="title-font font-medium text-white tracking-widest text-sm mb-3">CATEGORIES</h2>
          <nav class="list-none mb-10">
            <li>
              <a class="text-gray-400 hover:text-white">First Link</a>
            </li>
            <li>
              <a class="text-gray-400 hover:text-white">Second Link</a>
            </li>
            <li>
              <a class="text-gray-400 hover:text-white">Third Link</a>
            </li>
            <li>
              <a class="text-gray-400 hover:text-white">Fourth Link</a>
            </li>
          </nav>
        </div>
        <div class="lg:w-1/4 md:w-1/2 w-full px-4">
          <h2 class="title-font font-medium text-white tracking-widest text-sm mb-3">SUBSCRIBE</h2>
          <div class="flex xl:flex-nowrap md:flex-nowrap lg:flex-wrap flex-wrap justify-center items-end md:justify-start">
            <div class="relative w-40 sm:w-auto xl:mr-4 lg:mr-0 sm:mr-4 mr-2">
              <label for="footer-field" class="leading-7 text-sm text-gray-400">Placeholder</label>
              <input type="text" id="footer-field" name="footer-field" class="w-full bg-gray-800 rounded border bg-opacity-40 border-gray-700 focus:bg-transparent focus:ring-2 focus:ring-purple-900 focus:border-purple-500 text-base outline-none text-gray-100 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
            </div>
            <button class="lg:mt-2 xl:mt-0 flex-shrink-0 inline-flex text-white bg-purple-500 border-0 py-2 px-6 focus:outline-none hover:bg-purple-600 rounded">Button</button>
          </div>
          <p class="text-gray-500 text-sm mt-2 md:text-left text-center">Bitters chicharrones fanny pack
            <br class="lg:block hidden">waistcoat green juice
          </p>
        </div>
      </div>
    </div>
    <div class="bg-gray-800 bg-opacity-75">
      <div class="container px-5 py-6 mx-auto flex items-center sm:flex-row flex-col">
        <a class="flex title-font font-medium items-center md:justify-start justify-center text-white">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-purple-500 rounded-full" viewBox="0 0 24 24">
            <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
          </svg>
          <span class="ml-3 text-xl">Python Developmet</span>
        </a>
        <p class="text-sm text-gray-400 sm:ml-6 sm:mt-0 mt-4">© 2022 Iskander's Group —
          <a href="https://t.me/Ktocto_ya2" class="text-gray-500 ml-1" target="_blank" rel="noopener noreferrer">@Ktocto_ya2</a>
        </p>
        <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
          <a class="text-gray-400">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
            </svg>
          </a>
          <a class="ml-3 text-gray-400">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
            </svg>
          </a>
          <a class="ml-3 text-gray-400">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
              <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
            </svg>
          </a>
          <a class="ml-3 text-gray-400">
            <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
              <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
              <circle cx="4" cy="4" r="2" stroke="none"></circle>
            </svg>
          </a>
        </span>
      </div>
    </div>
  </footer>

templates/landing-page.html
{% extends 'base.html' %}

{% block title %}
  Landing-page
{% endblock %}

{% block content %}
  <section class="text-gray-400 bg-gray-900 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="-my-8 divide-y-2 divide-gray-800">
        <div class="py-8 flex flex-wrap md:flex-nowrap">
          <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
            <span class="font-semibold title-font text-white">News</span>
          </div>
          <div class="md:flex-grow">
            <h2 class="text-2xl font-medium text-white title-font mb-2">Bitters hashtag waistcoat fashion axe chia unicorn</h2>
            <p class="leading-relaxed">Glossier echo park pug, church-key sartorial biodiesel vexillologist pop-up snackwave ramps cornhole. Marfa 3 wolf moon party messenger bag selfies, poke vaporware kombucha lumbersexual pork belly polaroid hoodie portland craft beer.</p>
            <a class="text-purple-400 inline-flex items-center mt-4" href="{% url 'news:news_list' %}">
              Learn More
              <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path d="M5 12h14"></path>
                <path d="M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
        <div class="py-8 flex border-t-2 border-gray-800 flex-wrap md:flex-nowrap">
          <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
            <span class="font-semibold title-font text-white">Films</span>
          </div>
          <div class="md:flex-grow">
            <h2 class="text-2xl font-medium text-white title-font mb-2">Meditation bushwick direct trade taxidermy shaman</h2>
            <p class="leading-relaxed">Glossier echo park pug, church-key sartorial biodiesel vexillologist pop-up snackwave ramps cornhole. Marfa 3 wolf moon party messenger bag selfies, poke vaporware kombucha lumbersexual pork belly polaroid hoodie portland craft beer.</p>
            <a class="text-purple-400 inline-flex items-center mt-4" href="{% url 'post:post_list' %}">
              Learn More
              <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path d="M5 12h14"></path>
                <path d="M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/navbar.html
<header class="text-gray-400 bg-gray-900 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-purple-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">Python Development</span>
      </a>
      <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-700	flex flex-wrap items-center text-base justify-center">
        <a href="{% url 'landing_page' %}" class="mr-5 hover:text-white">Home</a>
        <a href="{% url 'news:news_list' %}" class="mr-5 hover:text-white">News</a>
        <a href="{% url 'post:post_list' %}" class="mr-5 hover:text-white">Films</a>
      </nav>

      {% if user.is_authenticated %}
        <div class="mx-3 text-gray-500 hover:text-gray-400">
          <a href="{% url 'logout' %}">Log out</a>
        </div>
        <div>
          <div class="ml-9 text-base font-medium leading-none text-white">{{user.username}}</div>
          <div class="text-sm font-medium leading-none text-gray-400">{{user.email}}</div>
        </div>
      
      {% else %}
      <a href="{% url 'login' %}">
        <button class="mx-3 text-gray-500 hover:text-gray-400">
          Log in
        </button>
      </a>
      <button class="inline-flex items-center bg-gray-800 border-0 py-1 px-3 
        focus:outline-none hover:bg-gray-700 rounded text-base mt-4 md:mt-0">
        Sign-Up
      </button>
      {% endif %}
    </div>
</header>